### ISSUE TITLE
curator 3.x is not backwards compatible with ZK 3.4

### ISSUE THREAD

**Issue by stantonk** [dropwizard/dropwizard-discovery#14]
While Curator 2.x is compatible with both ZK 3.4 and 3.5.

Seems way better to stick with 2.x until the next minor release of ZK (3.6)

```
INFO  [2016-04-14 15:22:42,595] org.apache.curator.framework.imps.EnsembleTracker: New config event received: null
INFO  [2016-04-14 15:22:42,596] org.eclipse.jetty.server.Server: jetty-9.2.9.v20150224
ERROR [2016-04-14 15:22:42,600] org.apache.curator.framework.imps.CuratorFrameworkImpl: Background exception was not retry-able or retry gave up
! java.lang.NullPointerException: null
! at java.io.ByteArrayInputStream.<init>(ByteArrayInputStream.java:106) ~[na:1.8.0_65]
! at org.apache.curator.framework.imps.EnsembleTracker.processConfigData(EnsembleTracker.java:163) ~[curator-framework-3.0.0.jar:na]
! at org.apache.curator.framework.imps.EnsembleTracker.access$200(EnsembleTracker.java:48) ~[curator-framework-3.0.0.jar:na]
! at org.apache.curator.framework.imps.EnsembleTracker$2.processResult(EnsembleTracker.java:134) ~[curator-framework-3.0.0.jar:na]
! at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:829) [curator-framework-3.0.0.jar:na]
! at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:611) [curator-framework-3.0.0.jar:na]
! at org.apache.curator.framework.imps.WatcherRemovalFacade.processBackgroundOperation(WatcherRemovalFacade.java:151) [curator-framework-3.0.0.jar:na]
! at org.apache.curator.framework.imps.GetConfigBuilderImpl$2.processResult(GetConfigBuilderImpl.java:210) [curator-framework-3.0.0.jar:na]
! at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:619) [zookeeper-3.5.1-alpha.jar:3.5.1-alpha-1693007]
! at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:528) [zookeeper-3.5.1-alpha.jar:3.5.1-alpha-1693007]
```

```
The are currently two released versions of Curator, 2.x.x and 3.x.x:

Curator 2.x.x - compatible with both ZooKeeper 3.4.x and ZooKeeper 3.5.x
Curator 3.x.x - compatible only with ZooKeeper 3.5.x and includes support for new features such as dynamic reconf
```

http://curator.apache.org/

**Comment by EdwardLee03** [comment]
问题根源：curator-recipes 3.1.0版本中(EnsembleTracker.java:153)存在bug(server.clientAddr = null)，会引起NPE异常； 3.2.1+版本已修复此问题，但建议使用最新的3.x.x。（结论：玩中间件要记得版本问题）

**Comment by EdwardLee03** [comment]
see [CURATOR-284](https://issues.apache.org/jira/browse/CURATOR-284) for v3.1.0 fixed

**Comment by jplock** [comment]
Looks like Curator v4.0.0 supports all ZK versions - http://curator.apache.org/zk-compatibility.html
